---

- name: set settings
  command: gsettings set "{{ item.schema }}" "{{ item.key }}" "{{ item.value }}"
  with_items:
    - { schema: 'org.gnome.desktop.media-handling', key: 'autorun-never', value: 'true' }
