---

- hosts: localhost
  roles:

    - sources
    - languages
    - {
      role: 'network',
      hosts: [
        { ip: '192.168.1.50', name: 'c4' },
      ],
    }
    - inotify
    - devices
    - tlp
    - powertop

    - apport
    - calculator
    - gparted
    - libreoffice
    - {
      role: 'nautilus',
      bookmarks: [
        'file:///home/sel/www ~/www',
        'file:///var/www /var/www',
      ],
      folders: [
        { path: "{{ ansible_env.HOME }}/www", icon: 'network' },
      ],
    }
    - rar
    - terminal
    - unetbootin

    - avconv
    - easytag
    - eog
    - rhythmbox
    - gimp
    - vlc
    - kodi
    - totem

    - owncloud

    - autorun
    - {
      role: 'wallpaper',
      uri: 'file://{{ ansible_env.HOME }}/Pictures/wallpapers/unsplash.com/unsplash.com-1.xml',
    }
    - {
      role: 'gtk',
      theme: 'Numix',
    }
    - {
      role: 'compiz',
      settings: [
        { schema: 'org.compiz.place:/org/compiz/profiles/unity/plugins/place/', key: 'viewport-matches', value: "['class=Thunderbird', 'class=Slack', 'name=trello.com']" },
        { schema: 'org.compiz.place:/org/compiz/profiles/unity/plugins/place/', key: 'viewport-x-values', value: '[2, 2, 2]' },
        { schema: 'org.compiz.place:/org/compiz/profiles/unity/plugins/place/', key: 'viewport-y-values', value: '[1, 1, 2]' },
        { schema: 'org.compiz.resize:/org/compiz/profiles/unity/plugins/resize/', key: 'mode', value: '2' },
        { schema: 'org.compiz.resize:/org/compiz/profiles/unity/plugins/resize/', key: 'resize-from-center', value: 'true' },
      ],
    }
    - datetime
    - {
      role: 'icons',
      theme: 'Numix-Circle',
    }
    - indicator-sysmonitor
    - textlines-indicator
    - keybindings
    - notifications
    - redshift

    - my-weather-indicator
    - slack
    - skype
    - plowshare
    - {
      role: "chromium-browser",
      trello_username: "simondubois",
    }

    - atom
    - avocode
    - desk
    - git
    - mysql-workbench
    - tilda
    - trash-cli
    - virtualbox
    # - ssh

    - {
      role: 'unity',
      settings: [
        { schema: 'com.canonical.Unity.Launcher', key: 'favorites', value: "['application://nautilus.desktop', 'application://chromium-browser.desktop', 'application://thunderbird.desktop', 'application://slack.desktop', 'application://atom.desktop', 'application://gnome-terminal.desktop', 'application://chrome-https___trello.com_.desktop', 'unity://running-apps', 'unity://expo-icon', 'unity://devices']" },
      ],
    }
    - {
      role: startup,
      enable: [
        '/usr/share/applications/extras-my-weather-indicator.desktop',
        '/usr/share/applications/indicator-sysmonitor.desktop',
        '/usr/share/applications/owncloud.desktop',
        '/usr/share/applications/redshift-gtk.desktop',
        '/usr/share/applications/slack.desktop',
        '/usr/share/applications/thunderbird.desktop',
        '/usr/share/applications/tilda.desktop',
        "{{ ansible_env.HOME }}/.local/share/applications/chrome-https___trello.com_.desktop",
        "{{ ansible_env.HOME }}/.local/share/applications/textlines-indicator.desktop",
      ],
    }
