---

- include_vars: background.yml

- name: list slideshow builders
  find:
    path: "{{ background_folder }}"
    pattern: "slideshowBuilder.py"
    recurse: yes
  register: slideshow_builder_list

- name: build background slideshows
  command: python "{{ item.path }}"
  with_items: "{{ slideshow_builder_list.files }}"

- name: gsettings options
  command: gsettings set "{{ item.schema }}" "{{ item.key }}" "{{ item.value }}"
  with_items: "{{ gsettings_options }}"
  when: background_options is defined

- name: gsettings uri
  command: gsettings set "{{ item.schema }}" "{{ item.key }}" "{{ item.value }}"
  with_items: "{{ gsettings_uri }}"
  when: background_uri is defined
