---

- include_vars: background.yml

- name: gsettings options
  command: gsettings set "{{ item.schema }}" "{{ item.key }}" "{{ item.value }}"
  with_items: "{{ gsettings_options }}"
  when: background_options is defined

- name: gsettings uri
  command: gsettings set "{{ item.schema }}" "{{ item.key }}" "{{ item.value }}"
  with_items: "{{ gsettings_uri }}"
  when: background_uri is defined
