---

- include_vars: background.yml

- name: list background folders
  find:
    paths: "{{ background_folder }}"
    file_type: directory
  register: background_folder_list

- name: build background slideshows
  command: python {{ item.path }}/slideshowBuilder.py
  with_items:
    - background_folder_list

- name: gsettings options
  command: gsettings set "{{ item.schema }}" "{{ item.key }}" "{{ item.value }}"
  with_items: "{{ gsettings_options }}"
  when: background_options is defined

- name: gsettings uri
  command: gsettings set "{{ item.schema }}" "{{ item.key }}" "{{ item.value }}"
  with_items: "{{ gsettings_uri }}"
  when: background_uri is defined
