---

- include_vars: notifications.yml

- name: add libnotify ppa
  apt_repository:
    repo: "{{ libnotify_ppa }}"
    state: present
  become: yes
  become_user: root

- name: upgrade libnotify
  apt:
    upgrade: dist
  become: yes
  become_user: root

- name: set libnotify configuration
  file:
    src: "{{ configuration_source }}"
    dest: "{{ configuration_destination }}"
    state: link

- name: restart libnotify
  command: pkill notify-osd
  ignore_errors: yes
