
gsettings:
  - { schema: 'org.gnome.desktop.media-handling', key: 'autorun-never', value: 'true' }

mimeapps_source: "{{ role_path }}/files/actions/mimeapps.list"

mimeapps_destination: "{{ ansible_env.HOME }}/.local/share/applications/mimeapps.list"
