---

- include: apport.yml
- include: bash.yml
- include: calculator.yml
- include: gparted.yml
- include: nautilus.yml
- include: rar.yml
- include: ssh.yml
- include: startup.yml
- include: unetbootin.yml
