---

- include_vars: ssh.yml

- name: get ssh config destination status
  stat:
    path: "{{ ssh_destination }}"
  register: ssh_destination_status

- name: delete previous ssh destination
  file:
    dest: "{{ ssh_destination }}"
    state: absent
  when: ssh_destination_status.stat.isdir is defined and ssh_destination_status.stat.isdir

- name: copy ssh config
  file:
    src: "{{ ssh_source }}"
    dest: "{{ ssh_destination }}"
    state: link
    force: yes

- name: get private keys
  find:
    paths: "{{ ssh_source }}/keys"
    patterns: "*_rsa"
  register: private_keys

- name: chmod private keys
  file:
    path: "{{ item }}"
    mode: 0600
  with_items: "{{ private_keys }}"
  become: yes
  become_user: root

- name: get public keys
  find:
    paths: "{{ ssh_source }}/keys"
    patterns: "*_rsa.pub"
  register: public_keys

- name: chmod public keys
  file:
    path: "{{ item }}"
    mode: 0644
  with_items: "{{ public_keys }}"
  become: yes
  become_user: root
