---

- include_vars: startup.yml

- name: create startup application directory
  file:
    path: "{{ destination }}"
    state: directory

- name: copy startup applications to disable
  copy:
    src: "{{ system_source }}/{{ item }}"
    dest: "{{ destination }}/{{ item }}"
    force: no
  with_items: "{{ disabled }}"

- name: disable startup applications
  lineinfile:
    dest: "{{ destination }}/{{ item }}"
    regexp: '^X-GNOME-Autostart-enabled=true$'
    line: 'X-GNOME-Autostart-enabled=false'
  with_items: "{{ disabled }}"

- name: copy startup applications to enable
  copy:
    src: "{{ item }}"
    dest: "{{ destination }}/{{ item | basename }}"
    force: no
  with_items: "{{ startup_enabled|default([]) }}"

- name: enable startup applications
  lineinfile:
    dest: "{{ destination }}/{{ item | basename }}"
    line: 'X-GNOME-Autostart-enabled=true'
  with_items: "{{ startup_enabled|default([]) }}"
