---

- name: add ppa
  apt_repository:
    repo: 'ppa:numix/ppa'
  when: "theme == 'Numix-Circle' or theme == 'Numix-Square'"
  become: yes
  become_user: root

- name: install numix-icon-theme
  apt:
    name: numix-icon-theme
  when: "theme == 'Numix-Circle' or theme == 'Numix-Square'"
  become: yes
  become_user: root

- name: install numix-icon-theme-circle
  apt:
    name: numix-icon-theme-circle
  when: "theme == 'Numix-Circle'"
  become: yes
  become_user: root

- name: install numix-icon-theme-square
  apt:
    name: numix-icon-theme-square
  when: "theme == 'Numix-Square'"
  become: yes
  become_user: root

- name: set icons
  command: gsettings set "{{ item.schema }}" "{{ item.key }}" "{{ item.value }}"
  with_items:
    - { schema: 'org.gnome.desktop.interface', key: 'icon-theme', value: "{{ theme }}" }
