
examples_path: "{{ ansible_env.HOME }}/examples.desktop"

bookmarks_file: "{{ ansible_env.HOME }}/.config/gtk-3.0/bookmarks"

gsettings:
  - { schema: 'org.gnome.nautilus.icon-view', key: 'default-zoom-level', value: 'larger' }
  - { schema: 'org.gnome.nautilus.list-view', key: 'use-tree-view', value: 'true' }
