
system_source: /etc/xdg/autostart/

application_source: /usr/share/applications/

destination: "{{ ansible_env.HOME }}/.config/autostart"

disabled:
  - deja-dup-monitor.desktop
  - onboard-autostart.desktop
  - orca-autostart.desktop
  - telepathy-indicator.desktop
  - update-notifier.desktop
  - vino-server.desktop
