---

- name: show all startup applications
  lineinfile:
    dest: "{{ item }}"
    regexp: '^NoDisplay=true$'
    line: 'NoDisplay=false'
    state: present
  with_fileglob:
    - /etc/xdg/autostart/*
  become: yes
  become_user: root

- name: Create startup application directory
  file:
    path: "{{ ansible_env.HOME }}/.config/autostart"
    state: directory

- name: copy startup applications
  copy:
    src: "/etc/xdg/autostart/{{ disabled_autostart }}"
    dest: "{{ ansible_env.HOME }}/.config/autostart/{{ disabled_autostart }}"

- name: disable startup applications
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.config/autostart/{{ disabled_autostart }}"
    regexp: '^X-GNOME-Autostart-enabled=true$'
    line: 'X-GNOME-Autostart-enabled=false'
    state: present
