---

- include_vars: autostart.yml

- name: show all startup applications
  lineinfile:
    dest: "{{ item }}"
    regexp: '^NoDisplay=true$'
    line: 'NoDisplay=false'
    state: present
  with_fileglob:
    - "{{ autostart_source }}/*"
  become: yes
  become_user: root

- name: create startup application directory
  file:
    path: "{{ autostart_destination }}"
    state: directory

- name: get startup application file infos
  stat:
    path: "{{ autostart_destination }}/{{ item }}"
  with_items: get_disabled_autostart
  register: get_disabled_autostart

- name: copy startup applications
  copy:
    src: "{{ autostart_source }}/{{ item }}"
    dest: "{{ autostart_destination }}/{{ item }}"
  with_items: get_disabled_autostart
  when: item.stat.exists == false

- name: disable startup applications
  lineinfile:
    dest: "{{ autostart_destination }}/{{ item }}"
    regexp: '^X-GNOME-Autostart-enabled=true$'
    line: 'X-GNOME-Autostart-enabled=false'
    state: present
  with_items: disabled_autostart
