---

- name: add flirc ppa
  apt_repository:
    repo: deb http://apt.flirc.tv/arch/i386 binary/
    state: present
    update_cache: no
  become: yes
  become_user: root

- name: add kodi ppa
  apt_repository:
    repo: ppa:team-xbmc/ppa
    state: present
    update_cache: no
  become: yes
  become_user: root

- name: add numix ppa
  apt_repository:
    repo: ppa:numix/ppa
    state: present
    update_cache: no
  become: yes
  become_user: root

- name: add my-weather-indicator ppa
  apt_repository:
    repo: ppa:atareao/atareao
    state: present
    update_cache: no
  become: yes
  become_user: root

- name: add plowshare ppa
  apt_repository:
    repo: ppa:plowsharepackagers/daily
    state: present
    update_cache: no
  become: yes
  become_user: root

- name: add tlp ppa
  apt_repository:
    repo: ppa:linrunner/tlp
    state: present
    update_cache: no
  become: yes
  become_user: root



