---

- name: add numix ppa
  apt_repository:
    repo: ppa:numix/ppa
    state: present
  become: yes
  become_user: root

- name: add my-weather-indicator ppa
  apt_repository:
    repo: ppa:atareao/atareao
    state: present
  become: yes
  become_user: root
