---

- name: uncomment repositories
  replace:
    backup: yes
    dest: /etc/apt/sources.list
    regexp: '^# deb http://archive.canonical.com/ubuntu(.+)$'
    replace: 'deb http://archive.canonical.com/ubuntu\1'
  become: yes
  become_user: root

- name: update sources
  apt: update_cache=yes
  become: yes
  become_user: root
