---

- include_vars: "sources.yml"

- name: remove default source file
  copy:
    path: /etc/apt/sources.list
    content: ''
  become: yes
  become_user: root

- name: enable package sources
  apt_repository:
    repo: "deb {{item}}"
    update_cache: no
  become: yes
  become_user: root
  with_items: "{{ enabled_sources }}"

- name: disable package sources
  apt_repository:
    repo: "deb {{item}}"
    state: absent
    update_cache: no
  become: yes
  become_user: root
  with_items: "{{ disabled_sources }}"

- name: update sources
  apt:
    update_cache: yes
    upgrade: dist
  become: yes
  become_user: root
