---

- include_vars: "sources.yml"

- name: enable package sources
  apt_repository:
    repo: deb {{item}}
    state: present
    update_cache: no
  become: yes
  become_user: root
  with_items: enabled_sources

- name: disable package sources
  apt_repository:
    repo: deb {{item}}
    state: absent
    update_cache: no
  become: yes
  become_user: root
  with_items: disabled_sources

- name: update sources
  apt:
    update_cache: yes
  become: yes
  become_user: root
