---

- name: add numix ppa
  apt_repository:
    repo: 'ppa:numix/ppa'
  become: yes
  become_user: root
  when: "theme == 'Numix'"

- name: install numix-gtk-theme
  apt:
    name: numix-gtk-theme
  become: yes
  become_user: root
  when: "theme == 'Numix'"

- name: add paper ppa
  apt_repository:
    repo: 'ppa:snwh/pulp'
  become: yes
  become_user: root
  when: "theme == 'Paper'"

- name: install paper-gtk-theme
  apt:
    name: paper-gtk-theme
  become: yes
  become_user: root
  when: "theme == 'Paper'"

- name: set settings
  command: gsettings set "{{ item.schema }}" "{{ item.key }}" "{{ item.value }}"
  with_items:
    - { schema: 'org.gnome.desktop.wm.preferences', key: 'theme', value: "{{ theme }}" }
    - { schema: 'org.gnome.desktop.interface', key: 'gtk-theme', value: "{{ theme }}" }
    - { schema: 'com.canonical.unity-greeter', key: 'theme-name', value: "{{ theme }}" }
