---

- name: empty default source file
  copy:
    dest: /etc/apt/sources.list
    content: ''
  become: yes
  become_user: root

- name: set source files mode
  file:
    path: /etc/apt/sources.list.d/
    mode: a+r
    recurse: yes
  become: yes
  become_user: root

- name: enable system sources
  apt_repository:
    repo: "deb {{item}}"
    update_cache: no
  with_items:
    - http://fr.archive.ubuntu.com/ubuntu {{ansible_distribution_release}} main
    - http://fr.archive.ubuntu.com/ubuntu {{ansible_distribution_release}} universe
    - http://fr.archive.ubuntu.com/ubuntu {{ansible_distribution_release}} restricted
    - http://fr.archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse
    - http://fr.archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-security main
    - http://fr.archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-security universe
    - http://fr.archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-security restricted
    - http://fr.archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-security multiverse
    - http://fr.archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates main
    - http://fr.archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates universe
    - http://fr.archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates restricted
    - http://fr.archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse
    - http://security.ubuntu.com/ubuntu {{ansible_distribution_release}} main
    - http://security.ubuntu.com/ubuntu {{ansible_distribution_release}} universe
    - http://security.ubuntu.com/ubuntu {{ansible_distribution_release}} restricted
    - http://security.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse
    - http://security.ubuntu.com/ubuntu {{ansible_distribution_release}}-security main
    - http://security.ubuntu.com/ubuntu {{ansible_distribution_release}}-security universe
    - http://security.ubuntu.com/ubuntu {{ansible_distribution_release}}-security restricted
    - http://security.ubuntu.com/ubuntu {{ansible_distribution_release}}-security multiverse
    - http://security.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates main
    - http://security.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates universe
    - http://security.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates restricted
    - http://security.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse
    - http://archive.canonical.com/ubuntu {{ansible_distribution_release}} partner
  become: yes
  become_user: root

- name: disable system sources
  apt_repository:
    repo: "deb {{item}}"
    state: absent
    update_cache: no
  with_items:
    - http://fr.archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-proposed universe
    - http://fr.archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-proposed restricted
    - http://fr.archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-proposed multiverse
    - http://fr.archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-backports universe
    - http://fr.archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-backports restricted
    - http://fr.archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-backports multiverse
    - http://security.ubuntu.com/ubuntu {{ansible_distribution_release}}-proposed universe
    - http://security.ubuntu.com/ubuntu {{ansible_distribution_release}}-proposed restricted
    - http://security.ubuntu.com/ubuntu {{ansible_distribution_release}}-proposed multiverse
    - http://security.ubuntu.com/ubuntu {{ansible_distribution_release}}-backports universe
    - http://security.ubuntu.com/ubuntu {{ansible_distribution_release}}-backports restricted
    - http://security.ubuntu.com/ubuntu {{ansible_distribution_release}}-backports multiverse
    - http://extras.ubuntu.com/ubuntu {{ansible_distribution_release}} main
  become: yes
  become_user: root

- name: update sources & packages
  apt:
    update_cache: yes
    upgrade: dist
    force: yes
  become: yes
  become_user: root
