---

- name: mysql folder
  file:
    path: "{{ ansible_env.HOME }}/www/mysql"
    state: directory

- name: mysql container
  docker:
    image: mysql:5.5
    name: mysql
    state: started
    restart_policy: always
    hostname: mysql
    volumes:
    - "{{ ansible_env.HOME }}/www/mysql:/var/lib/mysql"
    env:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
  become: yes
  become_user: root

- name: phpmyadmin container
  docker:
    image: phpmyadmin/phpmyadmin
    name: phpmyadmin
    state: started
    restart_policy: always
    links:
    - "mysql:mysql"
    ports:
    - "8080:80"
    volumes:
    - "{{ role_path }}/files/phpmyadmin.inc.php:/www/config.user.inc.php"
    env:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
      PMA_HOST: 'mysql'
      PMA_USER: 'root'
  become: yes
  become_user: root

- name: install mysql-workbench
  apt:
    name: mysql-workbench
  become: yes
  become_user: root
