---

- include_vars: guildwars2.yml

- name: add wine ppa
  apt_repository:
    repo: "{{ wine_ppa }}"
  become: yes
  become_user: root

- name: install wine
  apt:
    name: wine
  become: yes
  become_user: root
  register: install_wine

- name: install winetricks
  apt:
    name: winetricks
  become: yes
  become_user: root

- name: install d3dx9
  command: winetricks d3dx9
#  when: install_wine.changed

- name: create directory
  file:
    path: "{{ gw2_path }}"
    state: directory

- name: check setup
  stat:
    path: "{{ gw2_path }}/setup.exe"
  register: setup_file

- name: download gw2
  get_url:
    url: "{{ gw2_url }}"
    dest: "{{ gw2_path }}/setup.exe"
  when: setup_file.stat.exists == False

- name: install gw2
  shell: "wine explorer /desktop=gw2,1024x768 {{ gw2_path }}/setup.exe -dx9single &"
  when: setup_file.stat.exists == False

- name: copy icon
  file:
    src: "{{ icon_source }}"
    dest: "{{ icon_destination }}"
    state: link

- name: copy shortcut
  file:
    src: "{{ shortcut_source }}"
    dest: "{{ shortcut_destination }}"
    state: link
