---

- include_vars: guildwars2.yml

- name: add wine ppa
  apt_repository:
    repo: "{{ wine_ppa }}"
  become: yes
  become_user: root

- name: install wine
  apt:
    name: wine
  become: yes
  become_user: root

- name: create directory
  file:
    path: "{{ gw2_path }}"
    state: directory

- name: download gw2
  get_url:
    url: "{{ gw2_url }}"
    dest: "{{ gw2_path }}/setup.exe"

- name: install gw2
  command: "wine explorer /desktop=gw2,1024x768 {{ gw2_path }}/setup.exe -dx9single"
