---

- name: set settings
  command: gsettings set "{{ item.schema }}" "{{ item.key }}" "{{ item.value }}"
  with_items:
    - { schema: 'org.gnome.totem', key: 'autoload-subtitles', value: 'true' }
    - { schema: 'com.ubuntu.sound', key: 'allow-amplified-volume', value: 'true' }
