---

- name: clone plowshare repository
  git:
    repo: https://github.com/mcrapet/plowshare.git
    dest: /opt/plowshare
  become: yes
  become_user: root
  register: clone_plowshare

- name: install plowshare
  command: make install
  args:
    chdir: /opt/plowshare
  become: yes
  become_user: root
  when: clone_plowshare.changed

- name: install plowshare modules
  command: plowmod --install
  changed_when: false

- name: install screen
  apt:
    name: screen
  become: yes
  become_user: root

- name: install ddl script
  file:
    src: "{{ role_path }}/files/ddl"
    dest: "/usr/local/bin/ddl"
    mode: a+x
    state: link
  become: yes
  become_user: root

- name: chmod ddl script
  file:
    path: "{{ role_path }}/files/ddl"
    mode: a+x
