---

- name: set global user email
  git_config:
    name: user.email
    value: "simon@dubandubois.com"
    scope: global
  changed_when: false

- name: set global user name
  git_config:
    name: user.name
    value: "Simon Dubois"
    scope: global
  changed_when: false

- name: set global push default
  git_config:
    name: push.default
    value: "simple"
    scope: global
  changed_when: false

- name: set global core fileMode
  git_config:
    name: core.fileMode
    value: "false"
    scope: global
  changed_when: false

- name: set local core fileMode
  git_config:
    name: core.fileMode
    value: "false"
    scope: local
    repo: inventory_dir
  changed_when: false

- name: link excludesfile
  file:
    src: "{{ role_path }}/files/gitignore_global"
    dest: "~/.gitignore_global"
    state: link

- name: set global core excludesfile
  git_config:
    name: core.excludesfile
    value: "~/.gitignore_global"
    scope: global
  changed_when: false
