---

- name: set global user email
  git_config:
    name: user.email
    value: "simon@dubandubois.com"
    scope: global
  changed_when: false

- name: set global user name
  git_config:
    name: user.name
    value: "Simon Dubois"
    scope: global
  changed_when: false

- name: set global push default
  git_config:
    name: push.default
    value: "simple"
    scope: global
  changed_when: false

- name: set global core excludesfile
  git_config:
    name: core.excludesfile
    value: "{{ role_path }}/files/gitignore_global"
    scope: global
  changed_when: false
