---

- name: set global user email
  command: git config --global user.email "simon@dubandubois.com"
  changed_when: false

- name: set global user name
  command: git config --global user.name "Simon Dubois"
  changed_when: false

- name: set global push default
  command: git config --global push.default "simple"
  changed_when: false

- name: set global core excludesfile
  command: git config --global core.excludesfile "{{ role_path }}/files/gitignore_global"
  changed_when: false
