---

- name: set settings
  command: gsettings set "{{ item.schema }}" "{{ item.key }}" "{{ item.value }}"
  with_items:
    - { schema: 'org.gnome.eog.plugins', key: 'active-plugins', value: "['fullscreen', 'statusbar-date']" }
