
autostart_source: /etc/xdg/autostart/

autostart_destination: "{{ ansible_env.HOME }}/.config/autostart"

disabled_autostart:
  - deja-dup-monitor.desktop
  - onboard-autostart.desktop
  - orca-autostart.desktop
  - telepathy-indicator.desktop
  - update-notifier.desktop
  - vino-server.desktop
