---

- name: show all startup applications
  lineinfile:
    dest: "{{ item }}"
    regexp: '^NoDisplay=true$'
    line: 'NoDisplay=false'
    backrefs: yes
    state: present
  with_fileglob:
    - /etc/xdg/autostart/*

- name: disable startup applications
  copy:
    src: "/etc/xdg/autostart/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.conf/autostart/{{ item }}"
  with_items:
    - deja-dup-monitor.desktop
    - onboard-autostart.desktop
    - orca-autostart.desktop
    - telepathy-indicator.desktop
    - update-notifier.desktop
    - vino-server.desktop
