---

- name: show all autostart applications
  lineinfile:
    backup: yes
    dest: "{{ item }}"
    regexp: '^NoDisplay=true$'
    line: 'NoDisplay=false'
    backrefs: yes
    state: present
    with_fileglob:
      - /etc/xdg/autostart/*
