---

- name: show all startup applications
  lineinfile:
    dest: "{{ item }}"
    regexp: '^NoDisplay=true$'
    line: 'NoDisplay=false'
    backrefs: yes
    state: present
  with_fileglob:
    - /etc/xdg/autostart/*

- name: Create startup application directory
  file:
    path: "{{ ansible_env.HOME }}/.config/autostart"
    state: directory

- name: copy startup applications
  copy:
    src: "/etc/xdg/autostart/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/autostart/{{ item }}"
  with_items:
    - deja-dup-monitor.desktop
    - onboard-autostart.desktop
    - orca-autostart.desktop
    - telepathy-indicator.desktop
    - update-notifier.desktop
    - vino-server.desktop

- name: disable startup applications
  lineinfile:
    dest: "{{ item }}"
    regexp: '^X-GNOME-Autostart-enabled=true$'
    line: 'X-GNOME-Autostart-enabled=false'
    backrefs: yes
    state: present
  with_items:
    - deja-dup-monitor.desktop
    - onboard-autostart.desktop
    - orca-autostart.desktop
    - telepathy-indicator.desktop
    - update-notifier.desktop
    - vino-server.desktop
