---

- name: install powertop
  apt:
    name: powertop
  become: yes
  become_user: root
  register: install_powertop

# - name: calibrate powertop
#   command: powertop --calibrate
#   become: yes
#   become_user: root
#   when: install_powertop.changed

- name: autostart powertop
  lineinfile:
    dest: /etc/rc.local
    line: 'powertop --auto-tune'
    insertbefore: '^exit 0$'
  become: yes
  become_user: root

- name: set settings
  command: gsettings set "{{ item.schema }}" "{{ item.key }}" "{{ item.value }}"
  with_items:
    - { schema: 'com.canonical.indicator.power', key: 'show-percentage', value: 'true' }
    - { schema: 'com.canonical.indicator.power', key: 'show-time', value: 'true' }
    - { schema: 'org.gnome.desktop.screensaver', key: 'lock-enabled', value: 'false' }
    - { schema: 'org.gnome.settings-daemon.plugins.power', key: 'idle-dim', value: 'false' }
    - { schema: 'org.gnome.desktop.session', key: 'idle-delay', value: '0' }
    - { schema: 'org.gnome.settings-daemon.plugins.power', key: 'idle-dim', value: 'false' }
    - { schema: 'org.gnome.settings-daemon.plugins.power', key: 'lid-close-ac-action', value: 'nothing' }
    - { schema: 'org.gnome.settings-daemon.plugins.power', key: 'lid-close-battery-action', value: 'nothing' }
