---

- name: check bashrc
  stat:
    path: "{{ ansible_env.HOME }}/.bashrc"
  register: bashrc_file

- name: delete bashrc
  file:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    state: absent
  when: bashrc_file.stat.isreg

- name: link bashrc
  file:
    src: "{{ role_path }}/files/.bashrc"
    dest: "{{ ansible_env.HOME }}/.bashrc"
    state: link

- name: copy aliases
  file:
    src: "{{ role_path }}/files/.bash_aliases"
    dest: "{{ ansible_env.HOME }}/.bash_aliases"
    state: link

- name: download gitprompt
  get_url:
    url: "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
    dest: "{{ ansible_env.HOME }}/.bash_gitprompt"

- name: install undistract-me
  apt:
    name: undistract-me
  become: yes
  become_user: root

- name: set settings
  command: gconftool -s "{{ item.key }}" -t "{{ item.type }}" "{{ item.value }}"
  with_items:
    - { key: '/apps/gnome-terminal/profiles/Default/background_type', type: 'string', value: 'transparent' }
    - { key: '/apps/gnome-terminal/profiles/Default/background_darkness', type: 'float', value: '0.75' }
    - { key: '/apps/gnome-terminal/profiles/Default/background_color', type: 'string', value: '#151515' }
    - { key: '/apps/gnome-terminal/profiles/Default/foreground_color', type: 'string', value: '#A1B0B8' }
    - { key: '/apps/gnome-terminal/profiles/Default/palette', type: 'string', value: '#252525252525:#FFFF44443E3E:#C3C2D8D82C2B:#FFFFC1C13535:#4242A5A4F5F5:#0000ACACC1C1:#0000CDCBCDCB:#F5F5F5F5F5F5:#4CCC4CCC4CCC:#FFFF00000000:#0000FFFF0000:#FFFFFFFF0000:#46458281B4AE:#FFFF0000FFFF:#0000FFFFFFFF:#FFFFFFFFFFFF' }
    - { key: '/apps/gnome-terminal/profiles/Default/scrollback_unlimited', type: 'bool', value: 'true' }
    - { key: '/apps/gnome-terminal/profiles/Default/silent_bell', type: 'bool', value: 'true' }
    - { key: '/apps/gnome-terminal/profiles/Default/use_theme_colors', type: 'bool', value: 'false' }
