---

- include_vars: my-weather-indicator.yml

- name: add my-weather-indicator ppa
  apt_repository:
    repo: "{{ ppa }}"
    state: present
  become: yes
  become_user: root

- name: install my-weather-indicator
  apt:
    name: my-weather-indicator
    update_cache: yes
  become: yes
  become_user: root

- name: create my-weather-indicator configuration directory
  file:
    path: "{{ config_directory }}"
    state: directory

- name: set my-weather-indicator configuration
  file:
    src: "{{ config_source }}"
    dest: "{{ config_destination }}"
    state: link

- name: add my-weather-indicator startup
  copy:
    src: "{{ startup_source }}"
    dest: "{{ startup_destination }}"
    force: no
