---

- include_vars: my-weather-indicator.yml

- name: add my-weather-indicator ppa
  apt_repository:
    repo: "{{ ppa }}"
    state: present
  become: yes
  become_user: root

- name: install my-weather-indicator
  apt:
    name: my-weather-indicator
    update_cache: yes
  become: yes
  become_user: root
