---

- include_vars: my-weather-indicator.yml

- name: add my-weather-indicator ppa
  apt_repository:
    repo: "{{ ppa }}"
  become: yes
  become_user: root

- name: install my-weather-indicator
  apt:
    name: my-weather-indicator
  become: yes
  become_user: root

- name: create my-weather-indicator configuration directory
  file:
    path: "{{ config_directory }}"
    state: directory

- name: set my-weather-indicator configuration
  file:
    src: "{{ config_source }}"
    dest: "{{ config_destination }}"
    state: link

- name: edit my-weather-indicator icon path
  lineinfile:
    dest: "/usr/share/applications/extras-my-weather-indicator.desktop"
    regexp: '^Icon='
    line: "Icon=indicator-weather"
  become: yes
  become_user: root
