---

- include_vars: slack.yml

- name: get slack version
  shell: "dpkg-query --showformat='${Version}' --show slack || echo 0"
  register: installed_version
  changed_when: false

- name: download slack
  get_url:
    url: "{{ download_url }}"
    dest: "{{ download_path }}"
  when: installed_version.stdout != available_version

- name: install slack
  apt:
    deb: "{{ download_path }}"
  when: installed_version.stdout != available_version
  become: yes
  become_user: root
