---

- include_vars: kodi.yml

- name: add kodi ppa
  apt_repository:
    repo: "{{ kodi_ppa }}"
    state: present
  become: yes
  become_user: root

- name: install kodi
  apt:
    name: kodi
  become: yes
  become_user: root

- name: add flirc ppa
  apt_repository:
    repo: "{{ flirc_ppa }}"
    state: present
  become: yes
  become_user: root

- name: install flirc
  apt:
    name: flirc
    force: yes
  become: yes
  become_user: root
