
ppa: ppa:atareao/atareao

config_directory: "{{ ansible_env.HOME }}/.config/my-weather-indicator"

config_source: "{{ role_path }}/files/my-weather-indicator//my-weather-indicator.conf"

config_destination: "{{ config_directory }}/my-weather-indicator.conf"
