---

- include_vars: tilda.yml

- name: install tilda
  apt:
    name: tilda
  become: yes
  become_user: root

- name: set tilda configuration
  file:
    src: "{{ config_source }}"
    dest: "{{ config_destination }}"
    state: link
