---

- name: set settings
  command: gsettings set "{{ item.schema }}" "{{ item.key }}" "{{ item.value }}"
  with_items:
    - { schema: 'org.gnome.calculator', key: 'button-mode', value: 'advanced' }
    - { schema: 'org.gnome.calculator', key: 'number-format', value: 'fixed' }
