---

- include_vars: project-installer.yml

- name: create root folder
  file:
    path: "{{ root_path }}"
    state: directory
    mode: 0777
  become: yes
  become_user: root

- name: customize root folder
  command: "gvfs-set-attribute {{ root_path }} metadata::custom-icon-name network"

- name: link ubuntu-installer pull
  file:
    src: "{{ link_source }}"
    dest: "{{ link_destination }}"
    state: link
  when: 'git@github.com:simondubois/ubuntu-installer.git' in repositories

- name: install projects
  command: "ansible-pull -U {{ installer_source }} -e \"git_repository={{ item }} git_destination={{ root_path }}/{{ item | basename | regex_replace('.git$', '') }}\" -d {{ installer_destination }}"
  with_items: "{{ repositories }}"
