---

- name: list missing languages
  command: check-language-support
  register: missing_language_packages
  become: yes
  become_user: root
  changed_when: false

- name: install missing languages
  apt:
    name: "{{ missing_language_packages.stdout.split( ) }}"
  become: yes
  become_user: root
  when: missing_language_packages.stdout != ''
