---

- include_vars: plowshare.yml

- name: add plowshare ppa
  apt_repository:
    repo: "{{ ppa }}"
    state: present
    update_cache: yes
  become: yes
  become_user: root

- name: install plowshare
  apt:
    name: plowshare4
  become: yes
  become_user: root

- name: install plowshare
  apt:
    name: plowshare-modules
  become: yes
  become_user: root
