---

- include_vars: plowshare.yml

- name: clone plowshare repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_path }}"
  become: yes
  become_user: root
  register: clone_plowshare

- name: install plowshare
  command: make install
  args:
    chdir: "{{ repo_path }}"
  become: yes
  become_user: root
  when: clone_plowshare.changed
