---

- include_vars: configure.yml

- name: create ownclound configuration directory 1
  file:
    path: "{{ config_directory_1 }}"
    state: directory

- name: create ownclound configuration directory 2
  file:
    path: "{{ config_directory_2 }}"
    state: directory

- name: copy ownclound configuration file
  copy:
    src: "{{ config_source }}"
    dest: "{{ config_destination }}"
    force: no

- name: list sync folders
  command: grep -oP 'localPath=\K(.*)' "{{ config_destination }}"
  register: sync_folders

- debug:
    msg: "{{ sync_folders }}"

- name: create sync folders
  file:
    path: "{{ item.decode }}"
    state: directory
  with_items: sync_folders.stdout_lines
