
gsettings:
  - { schema: 'org.gnome.totem', key: 'auto-resize', value: 'true' }
  - { schema: 'org.gnome.totem', key: 'remember-position', value: 'true' }
  - { schema: 'org.gnome.totem', key: 'auto-subtitles', value: 'true' }
